added: open links in new tab - accidentally navigating away from current page is a pita! - also changed autofocus syntax (it does not need =true)
dwitter-net/dwitter-frontend pull request #104
Opened 2021-11-01 18:20 UTC by srmcgann

added: open links in new tab - accidentally navigating away from current page is a pita! - also changed autofocus syntax (it does not need =true)

2021-11-02 15:16 UTC, lionleaf requested changes
Having links from comments open in a new tab is a nice improvement, thanks!

However, I can't seem to get this to work locally, any idea what's going on? React is a bit fiddly sometimes.
Also, you've only modified the <Linkify> tag for the stickied "title"-comment at the top, not every comment.

2021-11-02 15:16 UTC, lionleaf commented on src/DweetCard.tsx
> +            <a target="blank" href={decoratedHref} key={key}>
For some reason I can't get this to work locally, inspecting the <a> element doesn't show a target property at all :|

Also, this <Linkify> is only for the "title" comment at the top of the dweet. I assume you'd want to add this to all comments as well, which you can do from the Linkify tag at line 603

2021-11-02 15:32 UTC, srmcgann commented
yes. heh. "_blank" is correct. The PR has been updated.

________________________________
From: Sigve Sebastian Farstad ***@***.***>
Sent: Tuesday, November 2, 2021 8:21 AM
To: dwitter-net/dwitter-frontend ***@***.***>
Cc: Scott R McGann ***@***.***>; Author ***@***.***>
Subject: Re: [dwitter-net/dwitter-frontend] added: open links in new tab - accidentally navigating away from current page is a pita! - also changed autofocus syntax (it does not need =true) (PR #104)


@sigvef commented on this pull request.

________________________________

In src/DweetCard.tsx<https://github.com/dwitter-net/dwitter-frontend/pull/104#discussion_r741188424>:

> @@ -497,7 +497,13 @@ export const DweetCard: React.FC<Props> = (props) => {
                 : 'none',
           }}
         >
-          <Linkify>{dweet.comments[0].text}</Linkify>
+          <Linkify componentDecorator={(decoratedHref, decoratedText, key) => (
+            <a target="blank" href={decoratedHref} key={key}>


I guess it should be target="_blank" https://css-tricks.com/targetblank/ .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/dwitter-net/dwitter-frontend/pull/104#discussion_r741188424>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEJ5RBJNPYFR7H7MLDNYVRDUJ76ZDANCNFSM5HEUBLFQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-11-02 21:23 UTC, lionleaf commented
Have you tested this locally? I can't seem to get to work as intended. Inspecting the links just gives me a plain <a href> tag

2021-11-09 23:38 UTC, lionleaf approved these changes

2021-11-09 23:39 UTC, lionleaf commented
Thanks for the implementation! I think there are still some cases that have the old behavior, but happy to get this merged in first.

2021-11-09 23:39 UTC, merged